import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./Providers";
import Menutemplate from "@/components/MenuComponent";
import Footer from "@/components/Footer";
import SmoothScrolling from "@/components/SmoothScroll";
import NewHeader from "@/components/NewHeader";
import GsapCustomCursor from "@/components/GsapCustomCursor";
import GptCustomCursor from "@/components/GptCustomCursor";
import LogoComponent from "@/components/LogoComponent";
import { ViewTransitions } from "next-view-transitions";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children, contact, newabout }) {
  return (
    <ViewTransitions>
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Menutemplate />
        <NewHeader />
          <SmoothScrolling>
            <GptCustomCursor />
            <div
              className="parent-container"
              style={{ display: "flex", flexDirection: "column" }}
            >
              {children}
              {contact}
              {newabout}
            </div>
          </SmoothScrolling>
          <Footer />
        </Provider>
      </body>
    </html>
    </ViewTransitions>
  );
}
