import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "./Providers";
import Footer from "@/components/Footer";
import SmoothScrolling from "@/components/SmoothScroll";
import NewHeader from "@/components/NewHeader";
import GptCustomCursor from "@/components/GptCustomCursor";
import NewMenuTemplateNoRouting from "@/components/NewMenuTemplateNoRouting";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <NewMenuTemplateNoRouting />
          <SmoothScrolling>
            <GptCustomCursor />
                                    <NewHeader />
<div id="menu-push-layer" />

           <div
  id="app-content"
  style={{
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    width: "100%",
  }}
>
  {children}
</div>

          </SmoothScrolling>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}

